[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet based on seq-Phragmén election method."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-elections-phragmen"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.0-alpha.2"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
serde = { version = "1.0.115", optional = true }
# darwinia
darwinia-support = { default-features = false, path = "../support" }
# substrate
frame-support     = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
frame-system      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-npos-elections = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-runtime        = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-std            = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }

[dev-dependencies]
# crates
hex-literal = { version = "0.3.1" }
# darwinia
darwinia-balances = { path = "../balances" }
# substrate
sp-core              = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-io                = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
substrate-test-utils = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }

[features]
default = ["std"]

std = [
	"crates-std",
	"darwinia-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"serde",
]
darwinia-std  = ["darwinia-support/std"]
substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-npos-elections/std",
	"sp-runtime/std",
	"sp-std/std",
]
